<?php
/**
 * @file
 * Code for the GHG Basic Content Types feature.
 */

include_once 'ghg_basic_content_types.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function ghg_basic_content_types_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['brief'] = array(
    'label' => t('Brief'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_block_info().
 */
function ghg_basic_content_types_block_info() {
  $blocks['footer'] = array(
    'info' => t('Footer'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['register'] = array(
    'info' => t('Register'),
  );
  $blocks['donate'] = array(
      'info' => t('Donate'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ghg_basic_content_types_block_view($delta = '') {
  switch ($delta) {
    case 'footer':
      $block['content'] = ghg_basic_content_types_footer();
      break;
    case 'register':
      $block['content'] = drupal_render(drupal_get_form('user_register_form'));
      break;
    case 'donate':
      $block['content'] = ghg_basic_content_types_donate_form();
      break;
  }
  
  return $block;
}

function ghg_basic_content_types_footer() {
  $items = array(
    '#markup' => "©2011 Gamers Helping Gamers",
  );
  return $items;
}


function ghg_basic_content_types_donate_form() {
  $items = array(
    '#markup' => 'We are a 501c3 corporation and our donations are tax deductible. Help a deserving young member of the Magic community go to college.<br/><br/><form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="MN7SLJZ6S36BA">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img align = "right" alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">',
  );
  return $items;
}
